name: Cypress Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Set the correct Node.js version you are using

    - name: Install dependencies
      run: npm ci

    - name: Ensure correct permissions
      run: chmod +x ./node_modules/.bin/cypress

    - name: Run Cypress tests with Mochawesome reporter
      run: npx cypress run --reporter mochawesome

       
